name: build
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./lexicon
    env:
      CI: false
      github_token: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./lexicon/build

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./lexicon/build
